tools:
    external_code_coverage: false
    php_code_coverage:      false
    php_code_sniffer:
        config: { standard: 'Ecg' }
    php_changetracking: false
    php_sim: false
    php_cs_fixer: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

build:
    tests:
        override:
            - true
    cache:
        directories: [ vendor/ ]

inherit: true

build_failure_conditions:
  - 'elements.rating(<= D).exists'
  - 'issues.new.exists'
  - 'project.metric("scrutinizer.quality", < 9.4)'