<?php
/**
 * @var $block \MX\HelperBar\Block\HelperBar
 */
?>
<?php if ($block->isEnabled()): ?>
    <div id="helper-bar" class="helper-bar helper-bar-<?= $block->getMode(); ?>">
        <span class="mage-mode column mage-mode-<?= $block->getMode(); ?>"></span>

        <span class="env column white vertically-centered">
            <?= $block->getEnvironmentName(); ?>
        </span>

        <span id="helper-bar-close" class="helper-bar-close" title="CTRL + `">X</span>

        <span id="product-metadata" class="env column white vertically-centered">
            <?= $block->getProductMetadata(); ?>
        </span>

        <script type="text/x-magento-init">
            {
                "#helper-bar": {
                    "MX_HelperBar/js/helperbar":
                    {
                        "closeSelector": "#helper-bar-close",
                        "commandSearchSelector": "#helper-bar-command-search"
                    }
                }
            }
        </script>
    </div>
<?php endif; ?>
