<?php
/**
 * @see \MX\HelperBar\Block\Adminhtml\HelperBar
 */
?>
<?php if ($block->isEnabled() && $block->isAllowed()): ?>
    <div id="helper-bar" class="helper-bar helper-bar-<?= $block->getMode(); ?>">
        <span class="mage-mode column mage-mode-<?= $block->getMode(); ?>"></span>

        <span class="env column white">
            <?= $block->getEnvironmentName(); ?>
        </span>

        <span class="env column">
            <input id="helper-bar-command-search">
        </span>

        <span id="product-metadata" class="env column white">
            <?= $block->getProductMetadata(); ?>
        </span>

        <span id="helper-bar-close" class="helper-bar-close" title="CTRL + `">X</span>
        <script type="text/x-magento-init">
            {
                "#helper-bar": {
                    "MX_HelperBar/js/helperbar":
                    {
                        "closeSelector": "#helper-bar-close",
                        "commandSearchSelector": "#helper-bar-command-search",
                        "commands": <?= /* @escapeNotVerified */ $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getCommands()); ?>
                    }
                }
            }
        </script>
    </div>
<?php endif; ?>
